# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    paths: 
      - rss-actions.py 
      - .github\workflows\python-app.yml
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 */24 * * *

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Upload generated feeds
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FIRST_NAME: Mona
        LAST_NAME: Octocat
      run: python rss-actions.py && git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/NoelNegash/rss-actions.git && git add . && git commit -m "generated feeds" && git push -u
